import {
  DEFAULT_EMERGENCY_NOTES,
  DEFAULT_INSURANCE,
  DEFAULT_MEDICATION_VERIFICATION,
  HealthRecord,
} from '@/types/health';
import { formatDate } from '@/utils/format';

export interface ExportCopy {
  emergencyMedicalRecord: string;
  generated: string;
  patientInformation: string;
  name: string;
  dob: string;
  bloodType: string;
  unknown: string;
  phone: string;
  notProvided: string;
  religiousPreference: string;
  emergencyContacts: string;
  primary: string;
  allergies: string;
  currentMedications: string;
  lastVerified: string;
  discontinuedMedications: string;
  discontinuedOn: string;
  currentConditions: string;
  diagnosed: string;
  procedureHistory: string;
  insurance: string;
  provider: string;
  policy: string;
  memberId: string;
  emergencyNotes: string;
  documentsOnFile: string;
  generatedByLine: string;
  patientGeneratedLine: string;
  verifyLine: string;
  emergencySummary: string;
  blood: string;
  meds: string;
  conditions: string;
  emergencyContact: string;
  dnrOnFile: string;
  organDonorOnFile: string;
  summaryVerifyLine: string;
}

export type ExportSectionKey =
  | 'personalDetails'
  | 'emergencyContacts'
  | 'allergies'
  | 'activeMedications'
  | 'discontinuedMedications'
  | 'conditions'
  | 'procedures'
  | 'insurance'
  | 'emergencyNotes'
  | 'documents';

export type ExportSelection = Record<ExportSectionKey, boolean>;

const DEFAULT_EXPORT_COPY: ExportCopy = {
  emergencyMedicalRecord: 'EMERGENCY MEDICAL RECORD',
  generated: 'Generated',
  patientInformation: 'PATIENT INFORMATION',
  name: 'Name',
  dob: 'DOB',
  bloodType: 'Blood Type',
  unknown: 'Unknown',
  phone: 'Phone',
  notProvided: 'Not provided',
  religiousPreference: 'Religious Preference',
  emergencyContacts: 'EMERGENCY CONTACTS',
  primary: 'PRIMARY',
  allergies: 'ALLERGIES',
  currentMedications: 'CURRENT MEDICATIONS',
  lastVerified: 'Last Verified',
  discontinuedMedications: 'DISCONTINUED MEDICATIONS',
  discontinuedOn: 'discontinued',
  currentConditions: 'CURRENT CONDITIONS',
  diagnosed: 'Diagnosed',
  procedureHistory: 'PROCEDURE HISTORY',
  insurance: 'INSURANCE',
  provider: 'Provider',
  policy: 'Policy',
  memberId: 'Member ID',
  emergencyNotes: 'EMERGENCY NOTES',
  documentsOnFile: 'DOCUMENTS ON FILE',
  generatedByLine: 'MyRecordsMyHealth.com — A MyBodyIsMyHealth.com product',
  patientGeneratedLine: 'This document was generated by the patient.',
  verifyLine: 'This is user-provided information. Verify with the patient or a licensed medical professional.',
  emergencySummary: '⚕ EMERGENCY SUMMARY',
  blood: 'Blood',
  meds: 'Meds',
  conditions: 'Conditions',
  emergencyContact: 'Emergency Contact',
  dnrOnFile: 'DNR: On file (see app for document)',
  organDonorOnFile: 'Organ Donor: On file (see app for document)',
  summaryVerifyLine: 'This is user-provided information. Verify with the patient or a licensed medical professional.',
};

const DEFAULT_EXPORT_SELECTION: ExportSelection = {
  personalDetails: true,
  emergencyContacts: true,
  allergies: true,
  activeMedications: true,
  discontinuedMedications: true,
  conditions: true,
  procedures: true,
  insurance: true,
  emergencyNotes: true,
  documents: true,
};

function resolveCopy(copy?: Partial<ExportCopy>): ExportCopy {
  return {
    ...DEFAULT_EXPORT_COPY,
    ...copy,
  };
}

function resolveSelection(selection?: Partial<ExportSelection>): ExportSelection {
  return {
    ...DEFAULT_EXPORT_SELECTION,
    ...selection,
  };
}

export function getDefaultExportSelection(): ExportSelection {
  return {
    ...DEFAULT_EXPORT_SELECTION,
  };
}

export function getNameOnlyExportSelection(): ExportSelection {
  return {
    personalDetails: false,
    emergencyContacts: false,
    allergies: false,
    activeMedications: false,
    discontinuedMedications: false,
    conditions: false,
    procedures: false,
    insurance: false,
    emergencyNotes: false,
    documents: false,
  };
}

export function getEnabledExportSections(selection: ExportSelection): ExportSectionKey[] {
  return (Object.keys(DEFAULT_EXPORT_SELECTION) as ExportSectionKey[]).filter((key) => selection[key]);
}

export function filterRecordForExport(record: HealthRecord, selection?: Partial<ExportSelection>): HealthRecord {
  const resolvedSelection = resolveSelection(selection);
  const activeMedications = record.medications.filter((medication) => medication.status !== 'discontinued');
  const discontinuedMedications = record.medications.filter((medication) => medication.status === 'discontinued');
  const filteredPersonalInfo = {
    ...record.personalInfo,
    dateOfBirth: resolvedSelection.personalDetails ? record.personalInfo.dateOfBirth : '',
    addressLine1: resolvedSelection.personalDetails ? record.personalInfo.addressLine1 : '',
    addressLine2: resolvedSelection.personalDetails ? record.personalInfo.addressLine2 : '',
    city: resolvedSelection.personalDetails ? record.personalInfo.city : '',
    state: resolvedSelection.personalDetails ? record.personalInfo.state : '',
    zipCode: resolvedSelection.personalDetails ? record.personalInfo.zipCode : '',
    phone: resolvedSelection.personalDetails ? record.personalInfo.phone : '',
    bloodType: resolvedSelection.personalDetails ? record.personalInfo.bloodType : '',
    religiousPreference: resolvedSelection.personalDetails ? record.personalInfo.religiousPreference : '',
  };

  return {
    ...record,
    personalInfo: filteredPersonalInfo,
    emergencyContacts: resolvedSelection.emergencyContacts ? record.emergencyContacts : [],
    allergies: resolvedSelection.allergies ? record.allergies : [],
    medications: [
      ...(resolvedSelection.activeMedications ? activeMedications : []),
      ...(resolvedSelection.discontinuedMedications ? discontinuedMedications : []),
    ],
    conditions: resolvedSelection.conditions ? record.conditions : [],
    procedures: resolvedSelection.procedures ? record.procedures : [],
    insurance: resolvedSelection.insurance ? record.insurance : { ...DEFAULT_INSURANCE },
    emergencyNotes: resolvedSelection.emergencyNotes ? record.emergencyNotes : { ...DEFAULT_EMERGENCY_NOTES },
    medicationVerification:
      resolvedSelection.activeMedications || resolvedSelection.discontinuedMedications
        ? record.medicationVerification
        : { ...DEFAULT_MEDICATION_VERIFICATION },
    documents: resolvedSelection.documents ? record.documents : [],
  };
}

export function generateEmergencyExport(record: HealthRecord, copy?: Partial<ExportCopy>): string {
  const labels = resolveCopy(copy);
  const divider = '─'.repeat(40);
  const lines: string[] = [];
  const fullName = [record.personalInfo.firstName, record.personalInfo.lastName].filter(Boolean).join(' ') || labels.notProvided;

  lines.push(labels.emergencyMedicalRecord);
  lines.push(labels.generated + ': ' + new Date().toLocaleString());
  lines.push(divider);

  lines.push('');
  lines.push(labels.patientInformation);
  lines.push(labels.name + ': ' + fullName);
  if (record.personalInfo.dateOfBirth) {
    lines.push(labels.dob + ': ' + formatDate(record.personalInfo.dateOfBirth));
  }
  if (record.personalInfo.bloodType) {
    lines.push(labels.bloodType + ': ' + record.personalInfo.bloodType);
  }
  if (record.personalInfo.phone) {
    lines.push(labels.phone + ': ' + record.personalInfo.phone);
  }
  if (record.personalInfo.religiousPreference) {
    lines.push(labels.religiousPreference + ': ' + record.personalInfo.religiousPreference);
  }

  if (record.emergencyContacts.length > 0) {
    lines.push('');
    lines.push(labels.emergencyContacts);
    record.emergencyContacts.forEach((contact) => {
      lines.push(
        '  ' +
          contact.name +
          ' (' +
          contact.relationship +
          ') - ' +
          contact.phone +
          (contact.isPrimary ? ' [' + labels.primary + ']' : '')
      );
    });
  }

  if (record.allergies.length > 0) {
    lines.push('');
    lines.push(labels.allergies);
    record.allergies.forEach((allergy) => {
      lines.push(
        '  ⚠ ' +
          allergy.name +
          ' - ' +
          allergy.severity.toUpperCase() +
          (allergy.reaction ? ' (' + allergy.reaction + ')' : '')
      );
    });
  }

  const activeMeds = record.medications.filter((medication) => medication.status !== 'discontinued');
  const discontinuedMeds = record.medications.filter((medication) => medication.status === 'discontinued');

  if (activeMeds.length > 0) {
    lines.push('');
    lines.push(labels.currentMedications);
    if (record.medicationVerification.lastVerifiedAt) {
      lines.push('  ' + labels.lastVerified + ': ' + formatDate(record.medicationVerification.lastVerifiedAt));
    }
    activeMeds.forEach((medication) => {
      lines.push('  • ' + medication.name + ' ' + medication.dosage + ' - ' + medication.frequency);
    });
  }

  if (discontinuedMeds.length > 0) {
    lines.push('');
    lines.push(labels.discontinuedMedications);
    discontinuedMeds.forEach((medication) => {
      lines.push(
        '  • ' +
          medication.name +
          ' ' +
          medication.dosage +
          (medication.discontinuedDate
            ? ' (' + labels.discontinuedOn + ' ' + formatDate(medication.discontinuedDate) + ')'
            : '')
      );
    });
  }

  if (record.conditions.length > 0) {
    lines.push('');
    lines.push(labels.currentConditions);
    record.conditions.forEach((condition) => {
      lines.push('  • ' + condition.name + ' - ' + labels.diagnosed + ': ' + formatDate(condition.diagnosedDate));
    });
  }

  if (record.procedures.length > 0) {
    lines.push('');
    lines.push(labels.procedureHistory);
    record.procedures.forEach((procedure) => {
      lines.push(
        '  • ' +
          procedure.name +
          ' - ' +
          formatDate(procedure.date) +
          (procedure.provider ? ' (' + procedure.provider + ')' : '')
      );
    });
  }

  if (
    record.insurance.provider ||
    record.insurance.policyNumber ||
    record.insurance.memberId ||
    record.insurance.phone
  ) {
    lines.push('');
    lines.push(labels.insurance);
    if (record.insurance.provider) {
      lines.push('  ' + labels.provider + ': ' + record.insurance.provider);
    }
    if (record.insurance.policyNumber) {
      lines.push('  ' + labels.policy + ': ' + record.insurance.policyNumber);
    }
    if (record.insurance.memberId) {
      lines.push('  ' + labels.memberId + ': ' + record.insurance.memberId);
    }
    if (record.insurance.phone) {
      lines.push('  ' + labels.phone + ': ' + record.insurance.phone);
    }
  }

  if (record.emergencyNotes.content) {
    lines.push('');
    lines.push(labels.emergencyNotes);
    lines.push('  ' + record.emergencyNotes.content);
  }

  if (record.documents.length > 0) {
    lines.push('');
    lines.push(labels.documentsOnFile);
    record.documents.forEach((document) => {
      lines.push(
        '  • ' +
          document.label +
          ' (' +
          document.type.replace(/_/g, ' ') +
          ')' +
          (document.notes ? ' - ' + document.notes : '')
      );
    });
  }

  lines.push('');
  lines.push(divider);
  lines.push(labels.generatedByLine);
  lines.push(labels.patientGeneratedLine);
  lines.push(labels.verifyLine);

  return lines.join('\n');
}

export function generateMinimalEmergencyExport(record: HealthRecord, copy?: Partial<ExportCopy>): string {
  const labels = resolveCopy(copy);
  const lines: string[] = [];
  const fullName = [record.personalInfo.firstName, record.personalInfo.lastName].filter(Boolean).join(' ') || labels.notProvided;

  lines.push(labels.emergencySummary);
  lines.push(fullName);
  if (record.personalInfo.bloodType) {
    lines.push(labels.blood + ': ' + record.personalInfo.bloodType);
  }
  if (record.personalInfo.religiousPreference) {
    lines.push(labels.religiousPreference + ': ' + record.personalInfo.religiousPreference);
  }

  if (record.allergies.length > 0) {
    lines.push(labels.allergies + ': ' + record.allergies.map((allergy) => allergy.name + ' (' + allergy.severity + ')').join(', '));
  }

  const activeMeds = record.medications.filter((medication) => medication.status !== 'discontinued');
  if (activeMeds.length > 0) {
    lines.push(labels.meds + ': ' + activeMeds.map((medication) => medication.name + ' ' + medication.dosage).join(', '));
  }

  if (record.conditions.length > 0) {
    lines.push(labels.conditions + ': ' + record.conditions.map((condition) => condition.name).join(', '));
  }

  if (record.emergencyContacts.length > 0) {
    const primaryContact = record.emergencyContacts.find((contact) => contact.isPrimary) || record.emergencyContacts[0];
    lines.push(labels.emergencyContact + ': ' + primaryContact.name + ' ' + primaryContact.phone);
  }

  if (record.documents.some((document) => document.type === 'dnr')) {
    lines.push(labels.dnrOnFile);
  }
  if (record.documents.some((document) => document.type === 'organ_donor')) {
    lines.push(labels.organDonorOnFile);
  }

  lines.push('');
  lines.push(labels.summaryVerifyLine);

  return lines.join('\n');
}
