import { HealthRecord } from '@/types/health';

const now = new Date().toISOString();
const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_HEALTH_RECORD: HealthRecord = {
  personalInfo: {
    firstName: 'Jordan',
    lastName: 'Reyes',
    dateOfBirth: '1978-05-14',
    addressLine1: '248 Lakeview Avenue',
    addressLine2: 'Apt 3B',
    city: 'Austin',
    state: 'TX',
    zipCode: '78704',
    phone: '(512) 555-0148',
    bloodType: 'O+',
    religiousPreference: 'None',
  },
  emergencyContacts: [
    {
      id: 'ec-1',
      name: 'Morgan Reyes',
      relationship: 'Spouse',
      phone: '(512) 555-0162',
      isPrimary: true,
    },
    {
      id: 'ec-2',
      name: 'Dr. Priya Shah',
      relationship: 'Primary Care Physician',
      phone: '(512) 555-0199',
      isPrimary: false,
    },
    {
      id: 'ec-3',
      name: 'Alex Reyes',
      relationship: 'Adult Child',
      phone: '(512) 555-0173',
      isPrimary: false,
    },
  ],
  allergies: [
    {
      id: 'al-1',
      name: 'Penicillin',
      severity: 'severe',
      reaction: 'Hives, difficulty breathing',
      source: 'Diagnosed by Dr. Shah, 2019',
      addedAt: daysAgo(120),
    },
    {
      id: 'al-2',
      name: 'Shellfish',
      severity: 'life-threatening',
      reaction: 'Anaphylaxis — carries EpiPen',
      source: 'Allergy panel, 2021',
      addedAt: daysAgo(90),
    },
    {
      id: 'al-3',
      name: 'Latex',
      severity: 'moderate',
      reaction: 'Contact dermatitis',
      source: 'Self-reported',
      addedAt: daysAgo(60),
    },
  ],
  medications: [
    {
      id: 'md-1',
      name: 'Lisinopril',
      dosage: '10 mg',
      frequency: 'Once daily (morning)',
      prescribedBy: 'Dr. Priya Shah',
      startDate: '2022-03-10',
      source: 'Prescription',
      addedAt: daysAgo(80),
      status: 'active',
      discontinuedDate: '',
    },
    {
      id: 'md-2',
      name: 'Atorvastatin',
      dosage: '20 mg',
      frequency: 'Once daily (evening)',
      prescribedBy: 'Dr. Priya Shah',
      startDate: '2023-01-05',
      source: 'Prescription',
      addedAt: daysAgo(70),
      status: 'active',
      discontinuedDate: '',
    },
    {
      id: 'md-3',
      name: 'Albuterol Inhaler',
      dosage: '90 mcg',
      frequency: 'As needed',
      prescribedBy: 'Dr. Nguyen (Pulmonology)',
      startDate: '2020-08-22',
      source: 'Prescription',
      addedAt: daysAgo(50),
      status: 'active',
      discontinuedDate: '',
    },
    {
      id: 'md-4',
      name: 'Vitamin D3',
      dosage: '2000 IU',
      frequency: 'Once daily',
      prescribedBy: 'Self',
      startDate: '2021-11-01',
      source: 'Over-the-counter',
      addedAt: daysAgo(40),
      status: 'active',
      discontinuedDate: '',
    },
  ],
  conditions: [
    {
      id: 'co-1',
      name: 'Hypertension',
      diagnosedDate: '2022-02-18',
      status: 'current',
      notes: 'Well-controlled on Lisinopril. Last BP reading 118/76.',
      source: 'Dr. Priya Shah',
      addedAt: daysAgo(100),
    },
    {
      id: 'co-2',
      name: 'Mild Asthma',
      diagnosedDate: '2020-07-30',
      status: 'current',
      notes: 'Triggered by seasonal allergens. Uses rescue inhaler occasionally.',
      source: 'Dr. Nguyen',
      addedAt: daysAgo(95),
    },
    {
      id: 'co-3',
      name: 'High Cholesterol',
      diagnosedDate: '2022-12-14',
      status: 'current',
      notes: 'Managed with atorvastatin and diet.',
      source: 'Dr. Priya Shah',
      addedAt: daysAgo(85),
    },
  ],
  procedures: [
    {
      id: 'pr-1',
      name: 'Appendectomy',
      date: '2014-06-12',
      provider: 'St. David\u2019s Medical Center',
      notes: 'Laparoscopic, no complications.',
      source: 'Hospital records',
      addedAt: daysAgo(75),
    },
    {
      id: 'pr-2',
      name: 'Colonoscopy (screening)',
      date: '2023-09-20',
      provider: 'Austin Gastro Associates',
      notes: 'Normal results. Next screening in 10 years.',
      source: 'Dr. Patel',
      addedAt: daysAgo(45),
    },
  ],
  insurance: {
    provider: 'Blue Cross Blue Shield of Texas',
    policyNumber: 'BCB-4820-9173',
    groupNumber: 'GRP-00284',
    memberId: 'XJR889204712',
    phone: '(800) 555-0134',
    planType: 'PPO',
  },
  emergencyNotes: {
    content:
      'Carries EpiPen in bag at all times due to shellfish allergy. Do NOT administer penicillin. Preferred hospital: St. David\u2019s Medical Center. Spouse Morgan Reyes is primary emergency contact and has medical decision authority.',
    updatedAt: daysAgo(10),
  },
  medicationVerification: {
    lastVerifiedAt: daysAgo(7),
    verifiedBy: 'user',
    status: 'verified',
  },
  documents: [
    {
      id: 'doc-1',
      type: 'organ_donor',
      label: 'Organ Donor Designation',
      fileUri: '',
      notes: 'Registered through Texas DMV.',
      addedAt: daysAgo(200),
      source: 'Texas Donor Registry',
    },
    {
      id: 'doc-2',
      type: 'medical_order',
      label: 'Advance Directive',
      fileUri: '',
      notes: 'On file with primary care physician.',
      addedAt: daysAgo(180),
      source: 'Dr. Priya Shah',
    },
  ],
  auditLog: [],
  lastUpdated: now,
  createdAt: daysAgo(365),
};
